### PR TITLE
Less magic numbers, and centralized theme install function.

### PR DESCRIPTION
**Pull request by LiquidFenrir**
only tested basic theme installing and shuffle, nobgm/bgm-only should work as well.

### CODE REVIEW

**Comment by Helloman892** [comment]
I'll bugtest when I have time - possibly tomorrow lunchtime, or if not then, tomorrow evening.

**Comment by Helloman892** [comment]
Well, other than my incredibly predictable complaint about the messed up icons, I haven't run into any issues yet. I'll post again once I manage to test BGM/no-BGM, as my console is dying.

**Comment by Helloman892** [comment]
Anyhow, I can't see any problems with this - it's achieved what the title suggests. Feel free to squash and merge this when you want to (in case you're not finished).

**Comment by LiquidFenrir** [comment]
Yeah it is finished, was only waiting for testing, thanks!

**Pull request merged**
