### PR TITLE
pls accept

### PR DESCRIPTION
**Pull request by kekmaster97**
[CHMM2-master.zip](https://github.com/astronautlevel2/Anemone3DS/files/1323288/CHMM2-master.zip)
complete overhaul, replaces everything with chmm2 so its better

### CODE REVIEW

**Comment by astronautlevel2** [comment]
¯\_( ͡° ͜ʖ ͡°)_/¯

**Comment by EdTheNerd** [comment]
i like turtles

**Comment by kekmaster97** [comment]
lazy dev wont update anemone, when i improve it they deny. wow astro

**Comment by lucario1001** [comment]
man astro wen you gonna make chmm3 
( ͡° ͜ʖ ͡°)

**Pull request closed without merging**
