### PR TITLE
Completed C++ rewrite

### PR DESCRIPTION
**Pull request by LiquidFenrir**
Hello, finally completed this thing I wanted to do. My last contribution. It shouldn't be able to crash, if nothing messes up.  
Fixes the infamous scroll crash by abusing events, and adds badge support.  
The only things missing are the install check/indicator, and a few touchscreen controls, that I thought wouldn't fit well.  
Based on an old redesign by kenn, it's not too hard to bring back to the old style if it doesn't please the crowd.  
HEAVILY NEEDS TESTING. If anything doesnt work before the merge, I'll try to fix it. Once it's merged, out of my hands.
Enjoy and have a nice day.

### CODE REVIEW

**Comment by catfatwm** [comment]
Was this impliminted?

**Comment by Helloman892** [comment]
Does it look like it was implemented?

**Comment by Helloman892** [comment]
Currently crashes on either launch or exit on new3DS. Looking for a fix, but it might be a bug in citro2d.

**Comment by Helloman892** [comment]
Now crashes on trying to download the theme list from Theme Plaza. Backtrace as follows:
```Thread 3 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 217]
ndspiReadChnState ()
    at /home/fincs/pacman-packages/libctru/src/ctrulib-1.6.0/libctru/source/ndsp/ndsp-channel.c:446
446     /home/fincs/pacman-packages/libctru/src/ctrulib-1.6.0/libctru/source/ndsp/ndsp-channel.c: No such file or directory.
(gdb) bt
#0  ndspiReadChnState ()
    at /home/fincs/pacman-packages/libctru/src/ctrulib-1.6.0/libctru/source/ndsp/ndsp-channel.c:446
#1  0x00159928 in ndspSync ()
    at /home/fincs/pacman-packages/libctru/src/ctrulib-1.6.0/libctru/source/ndsp/ndsp.c:344
Backtrace stopped: Cannot access memory at address 0x8020fdc
```
(ndsp yes!)

**Pull request closed without merging**
