### PR TITLE
Add badge support, and qr scanning autodetect

### PR DESCRIPTION
**Pull request by LiquidFenrir**
Should split big badges, as the code for converting is taken straight from GYTB which did it just fine, but untested
When scanning a QR code that links to a badge, it extracts all of them, keeping compatibility with GYTB

Unlike GYTB, it creates a homebrew badges set instead of deleting everything and writing over. That allows it to keep the previous content, and not get deleted by the Badge Arcade.

qr code to cia for testing:

### CODE REVIEW

**Comment by LiquidFenrir** [comment]
broken for now. will reopen when fixed

**Comment by leira** [comment]
Hi, @LiquidFenrir~ How is this PR now? Is there any plan to fix and merge it?

**Comment by LiquidFenrir** [comment]
No, badges suck, use GYTB if you want a dirty hack or AdvancedBadgeEditor to add them better on PC, I suggest not using any at all

**Comment by leira** [comment]
Thanks for the pointers~! Using GYTB wasn't fun at all, but I managed to get it done.

If you are willing to tolerate my ignorance a bit more, can you please elaborate why badges suck? It is totally fine if you don't feel like to~

**Pull request closed without merging**
